### ISSUE TITLE
Add cards to the top

### ISSUE THREAD

**Issue by berezovskyi** [walteranderson/add-to-trello#5]
Hi Walter,

I think I would greatly appreciate an ability to add the card to the top of the list. I am thinking of adding a button next to _Add_ in `popup.html` () and add a `pos` argument to the POST request in `submitCard`. It can also be one button with a split dropdown: http://getbootstrap.com/components/#btn-dropdowns-split.

Do you think you'd accept such a PR?

**Comment by walteranderson** [comment]
Hey @berezovskyi, this functionality will be added in the next release. You can see this [pull request](https://github.com/walteranderson/add-to-trello/pull/6) for more details.
