### ISSUE TITLE
Dropdown doesn't work on Vivaldi

### ISSUE THREAD

**Issue by DJDBgr** [walteranderson/add-to-trello#7]
The list selection dropdown doesn't work on Vuvaldi (i'm using version 1.3.537.5 32-bit). It shows nothing. This is what i get when i click there:

![vivaldi_2016-07-21_20-46-15](https://cloud.githubusercontent.com/assets/5906778/17032894/3654a5b4-4f84-11e6-8902-8028b567ddd4.jpg)

**Comment by walteranderson** [comment]
Hey @DJDBgr, since this is a Chrome extension, I don't think I will be adding support for Vivaldi any time soon, apologies.
